name: abiyefon
on:
  schedule:
    - cron:  0 0 * * 1
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  kadin_job:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"

