name: callererkek
on:
   workflow_dispatch:

env:
  WEBSITE: biraradamoda
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GENDER: erkek
jobs:
  network_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: network
      maxconcurrency: '1'
      WEBSITE: biraradamoda
      GENDER: erkek
    secrets: inherit
  # sementa_job:
  #   uses: ./.github/workflows/reusable.yml
  #   with:
  #     marka: sementa
  #     maxconcurrency: '1'
  #     WEBSITE: biraradamoda
  #     GENDER: erkek
  #   secrets: inherit
  penti_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: penti
      maxconcurrency: '1'
      WEBSITE: biraradamoda
      GENDER: erkek
    secrets: inherit
  defacto_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: defacto
      maxconcurrency: '1'
      WEBSITE: biraradamoda
      GENDER: erkek
    secrets: inherit
  koton_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: koton
      maxconcurrency: '1'
      WEBSITE: biraradamoda
      GENDER: erkek
    secrets: inherit
  lcwaikiki_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: lcwaikiki
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '10'
  mavi_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: mavi
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '1'
    secrets: inherit
  beymen_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: beymen
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '5'
    secrets: inherit
  vakko_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: vakko
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '1'
    secrets: inherit
  zara_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: zara
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '1'
    secrets: inherit
  hm_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: hm
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '1'
    secrets: inherit
  beyyoglu_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: beyyoglu
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '1'
    secrets: inherit
  colins_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: colins
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '10'
    secrets: inherit
  xint_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: xint
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '1'
    secrets: inherit
  tozlu_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: tozlu
      WEBSITE: biraradamoda
      GENDER: erkek
      maxconcurrency: '1'
    secrets: inherit
  # desa_job:
  #   uses: ./.github/workflows/reusable.yml
  #   with:
  #     marka: desa
  #     WEBSITE: biraradamoda
  #     maxconcurrency: '1'
  #   secrets: inherit
